#+TITLE: Information on goal setting 2024

Some videos and links on setting goals I found and my take aways. I normally set
goals but I haven't researched goal setting so this year so I thought I would.

* James Clear 'Goal setting'
The author of 'Atomic habbits' has a short post on goals and systems.
https://jamesclear.com/goal-setting

Take aways:

1. Select the right goals and limit the goals you're working on at once. I'm
   going to be working exercising and procrastinating less

2. Focus the systems to reach my goals. Focus on my day to day, week to week
   habits and actions and things that move me forward.

* Goals Toolkit: How to Set & Achieve Your Goals
From Huberman lab podcast
Length 1:34 hours. I only watched half so far.

https://youtu.be/CrtR12PBKb0?si=BDpe1m_n0OD7VKwJ

Take aways:
** Pick one goal to work on.
   I have 2 goals however I might just work on one if I fail at my number one
   priority.
** Don't make the goal too easy to achieve
   Pick a goal where the level of performance that is above what you think you can do something that's just out of reach.
** Measurable goal
   The verb action you are doing to do. Write it out on paper.
* How To Change Your Life In 30 Days With Reverse Goal Setting
From Cal Newport (author)
1:29 hours. I only watched half so far.

https://youtu.be/USOn1E6g2N0

More specific video on Reverse goal setting also called 'Backwards planning'
https://www.youtube.com/watch?v=7vQ9zxT6uhs. Haven't done the exercise from this.

The Cal Newport video has a good an insight:

He calls it 'Checklist productivity' people think the main thing separating them
from their hard goals is information. You underestimate the effort.

Hearing that I realized I seem to think I can eliminate most of the chance from
my life if I have the right information.

Instead maybe it would be better if I focus on my process and decision making instead.

* The Only Goal That Matters.
4 mins. https://www.youtube.com/watch?v=KOYNnHMPZGM

Take aways:
The outcome isn't the goal. The goal is who you become.
Sometimes we are blinded by the goal and don't look after our self's.

I wonder how I can give myself qualities like self compassion and resilience.

* How to Make 2024 The Best Year of Your Life
Ali Abdaal
https://www.youtube.com/watch?v=c_DOG_mXz5w

Take away:
- plan your ideal week.
  I did this is in Google calendar.

* Other things I did
** mood board
I did a mood board just with all the things I'm interested in doing in 2024. I
already have my top priority and it was good to just see what I'm interested in
doing.
** WOOP exercise
evidence based exersize for people to fulfill their wishes, set preferences, and
change their habits. https://woopmylife.org/

I'm trying it out to see if it works.

See this video if your interested in the information about 'WOOP'
also called Mental Contrasting with
Implementation Intentions'

https://youtu.be/Zz59q8wHECk?si=Zl4bvl5nDtT-5E3R

Here my result of the exercise

dec 28 2023

wish in the next 4 weeks - that I am disciplined

outcome - i will finally be free and not controlled by my desires

obstacle - my emotions that want to not work win

plan - i will use skills

- if i feel like not working then I will be mindful and use skills to help myself work
